SignalRWebUI/Controllers/QRCodeController.cs
using Microsoft.AspNetCore.Mvc;
using QRCoder;
using System.Drawing;
using System.Drawing.Imaging;

namespace SignalRWebUI.Controllers
{
    public class QRCodeController : Controller
    {

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Index( string value)
        {
            using (MemoryStream ms = new())
            {
                QRCodeGenerator CreateQRCode = new();
                QRCodeGenerator.QRCode squareCode = CreateQRCode.CreateQrCode(value, QRCodeGenerator.ECCLevel.Q);
                using (Bitmap image = squareCode.GetGraphic(10))
                {
                    image.Save(ms,ImageFormat.Png);
                    ViewBag.QRCodeImage = "data:image/png;base64," + Convert.ToBase64String(ms.ToArray());
                } 

            }
            return View();
        }
    }
}

SignalRWebUI/Views/QRCode/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/AdminLayout/Index.cshtml";
}
<div class="content">
    <div class="container-fluid">
        <h4 class="page-title">QR Code İşlemleri</h4>
        <div class="row">
            <div class="col-md-12">
                <form method="post" asp-action="Index" asp-controller="QRCode">
                    <input type="text" name="value" />
                    <input type="submit" value="QR Code Oluştur" class="btn btn-warning" />
                    <br />
                    <br />
                </form>
                @if (ViewBag.QRCodeImage != null)
                {
                    <img src="@ViewBag.QRCodeImage" alt="" style="width:400px;height:400px" />
                }
            </div>
        </div>
    </div>
</div>